version: '3'

services:
  service1:
    build: ./service1
    ports:
      - "8001:8001"
    networks:
      - app-network

  service2:
    build: ./service2
    ports:
      - "8002:8002"
    volumes:
      - ./service2/logs:/app/logs
    networks:
      - app-network
  
  login:
    build: ./login
    ports:
      - "8003:8003"
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge